# Generated by Django 5.1 on 2024-09-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('ciudad', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('fono', models.CharField(max_length=15)),
            ],
        ),
    ]
