# Generated by Django 5.1 on 2024-09-16 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_juego', models.IntegerField()),
                ('Id_categoria', models.IntegerField()),
                ('Descripcion', models.CharField(max_length=100)),
            ],
        ),
    ]
